# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_planet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroupmodel',
            unique_together=set([('user', 'group')]),
        ),
        migrations.AlterIndexTogether(
            name='usergroupmodel',
            index_together=set([]),
        ),
    ]
